spring:
  application:
    name: demo
  profiles:
    active: local
  output:
    ansi:
      enabled: always
  mvc:
    dispatch-trace-request: true
    dispatch-options-request: true
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static
    servlet:
      load-on-startup: 0
    format:
      date: yyyy-MM-dd HH:mm:ss
  messages:
    encoding: UTF-8
logging:
#  pattern:
#    console: '%d -%msg%n'
  level:
    root: info
#  file:
#    path: D:/www/logs/common